import type { Metadata } from "next";
import localFont from "next/font/local";
import "./styles/globals.scss";

import Header from "@/components/organisms/Header";
// import Footer from "@/components/organisms/Footer";
import { getFooterData, getHeaderData } from "@/lib/strapi-utils";

const generalSans = localFont({
  src: [
    {
      path: "./../fonts/generalsans-medium-webfont.woff2",
      weight: "500",
      style: "normal",
    },
    {
      path: "./../fonts/generalsans-semibold-webfont.woff2",
      weight: "600",
      style: "normal",
    },
    {
      path: "./../fonts/generalsans-bold-webfont.woff2",
      weight: "700",
      style: "normal",
    },
  ],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const headerData = await getHeaderData();
  const footerData = await getFooterData();
  console.log("footerData", footerData);

  return (
    <html lang="en">
      <body className={`${generalSans.className} ${generalSans.style}`}>
        <Header
          alert={headerData?.alert || undefined}
          menu={headerData?.menu || []}
          logo={headerData?.logo || undefined}
          showCompliance={headerData?.showCompliance}
          showSearch={headerData?.showSearch}
          contactUsLabel={headerData?.contactUsLabel}
          contactUsLink={headerData?.contactUsLink}
        />
        {children}
        {/* <Footer
          logo={footerData?.logo || undefined}
          brandDescription={footerData?.brandDescription}
          contactTitle={footerData?.contactTitle}
          contactDescription={footerData?.contactDescription}
          menu={footerData?.menu || []}
          socialLinks={footerData?.socialLinks || []}
          complianceBadges={footerData?.complianceBadges || []}
          contactCards={footerData?.contactCards || []}
        /> */}
      </body>
    </html>
  );
}
