import type { Metadata } from "next";
import localFont from "next/font/local";
import "./styles/globals.scss";
import { sharedContent } from "@/lib/content/shared-content";
import Header from "@/components/molecules/Header";
import Footer from "@/components/molecules/Footer";

const generalSans = localFont({
  src: [
    {
      path: "./../fonts/generalsans-medium-webfont.woff2",
      weight: "500",
      style: "normal",
    },
    {
      path: "./../fonts/generalsans-semibold-webfont.woff2",
      weight: "600",
      style: "normal",
    },
    {
      path: "./../fonts/generalsans-bold-webfont.woff2",
      weight: "700",
      style: "normal",
    },
  ],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${generalSans.className} ${generalSans.style}`}>
        <Header
          alert={sharedContent.header.alert}
          menu={sharedContent.header.menu}
        />
        {children}
        <Footer />
      </body>
    </html>
  );
}
